[package]
name = "tic_tac_toe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bevy = "0.13"
bevy_replicon = "0.23"
serde = { version = "1.0", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3